name: Check PR code quality

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, converted_to_draft]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-pr-code-quality:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run "check" script
        run: yarn run check

      - name: Run "test" script
        # TODO add support for coverage with PR feedback
        run: yarn run test
